// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package route

import (
	"context"
	"fmt"

	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	acktypes "github.com/aws-controllers-k8s/runtime/pkg/types"

	svcapitypes "github.com/aws-controllers-k8s/apigatewayv2-controller/apis/v1alpha1"
)

// ResolveReferences finds if there are any Reference field(s) present
// inside AWSResource passed in the parameter and attempts to resolve
// those reference field(s) into target field(s).
// It returns an AWSResource with resolved reference(s), and an error if the
// passed AWSResource's reference field(s) cannot be resolved.
// This method also adds/updates the ConditionTypeReferencesResolved for the
// AWSResource.
func (rm *resourceManager) ResolveReferences(
	ctx context.Context,
	apiReader client.Reader,
	res acktypes.AWSResource,
) (acktypes.AWSResource, error) {
	namespace := res.MetaObject().GetNamespace()
	ko := rm.concreteResource(res).ko.DeepCopy()
	err := validateReferenceFields(ko)
	if err == nil {
		err = resolveReferenceForAPIID(ctx, apiReader, namespace, ko)
	}
	if err == nil {
		err = resolveReferenceForAuthorizerID(ctx, apiReader, namespace, ko)
	}
	if err == nil {
		err = resolveReferenceForTarget(ctx, apiReader, namespace, ko)
	}

	// if the Target was provided using a reference, prepend "integrations/"
	// with the IntegrationId from TargetRef
	if ko.Spec.TargetRef != nil && ko.Spec.Target != nil {
		targetStr := fmt.Sprintf("integrations/%s", *ko.Spec.Target)
		ko.Spec.Target = &targetStr
	}

	if hasNonNilReferences(ko) {
		return ackcondition.WithReferencesResolvedCondition(&resource{ko}, err)
	}
	return &resource{ko}, err
}

// validateReferenceFields validates the reference field and corresponding
// identifier field.
func validateReferenceFields(ko *svcapitypes.Route) error {
	if ko.Spec.APIRef != nil && ko.Spec.APIID != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("APIID", "APIRef")
	}
	if ko.Spec.APIRef == nil && ko.Spec.APIID == nil {
		return ackerr.ResourceReferenceOrIDRequiredFor("APIID", "APIRef")
	}
	if ko.Spec.AuthorizerRef != nil && ko.Spec.AuthorizerID != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("AuthorizerID", "AuthorizerRef")
	}
	if ko.Spec.TargetRef != nil && ko.Spec.Target != nil {
		return ackerr.ResourceReferenceAndIDNotSupportedFor("Target", "TargetRef")
	}
	return nil
}

// hasNonNilReferences returns true if resource contains a reference to another
// resource
func hasNonNilReferences(ko *svcapitypes.Route) bool {
	return false || ko.Spec.APIRef != nil || ko.Spec.AuthorizerRef != nil || ko.Spec.TargetRef != nil
}

// resolveReferenceForAPIID reads the resource referenced
// from APIRef field and sets the APIID
// from referenced resource
func resolveReferenceForAPIID(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Route,
) error {
	if ko.Spec.APIRef != nil &&
		ko.Spec.APIRef.From != nil {
		arr := ko.Spec.APIRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty")
		}
		namespacedName := types.NamespacedName{
			Namespace: namespace,
			Name:      *arr.Name,
		}
		obj := svcapitypes.API{}
		err := apiReader.Get(ctx, namespacedName, &obj)
		if err != nil {
			return err
		}
		var refResourceSynced, refResourceTerminal bool
		for _, cond := range obj.Status.Conditions {
			if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
				cond.Status == corev1.ConditionTrue {
				refResourceSynced = true
			}
			if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
				cond.Status == corev1.ConditionTrue {
				refResourceTerminal = true
			}
		}
		if refResourceTerminal {
			return ackerr.ResourceReferenceTerminalFor(
				"API",
				namespace, *arr.Name)
		}
		if !refResourceSynced {
			return ackerr.ResourceReferenceNotSyncedFor(
				"API",
				namespace, *arr.Name)
		}
		if obj.Status.APIID == nil {
			return ackerr.ResourceReferenceMissingTargetFieldFor(
				"API",
				namespace, *arr.Name,
				"Status.APIID")
		}
		ko.Spec.APIID = obj.Status.APIID
	}
	return nil
}

// resolveReferenceForAuthorizerID reads the resource referenced
// from AuthorizerRef field and sets the AuthorizerID
// from referenced resource
func resolveReferenceForAuthorizerID(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Route,
) error {
	if ko.Spec.AuthorizerRef != nil &&
		ko.Spec.AuthorizerRef.From != nil {
		arr := ko.Spec.AuthorizerRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty")
		}
		namespacedName := types.NamespacedName{
			Namespace: namespace,
			Name:      *arr.Name,
		}
		obj := svcapitypes.Authorizer{}
		err := apiReader.Get(ctx, namespacedName, &obj)
		if err != nil {
			return err
		}
		var refResourceSynced, refResourceTerminal bool
		for _, cond := range obj.Status.Conditions {
			if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
				cond.Status == corev1.ConditionTrue {
				refResourceSynced = true
			}
			if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
				cond.Status == corev1.ConditionTrue {
				refResourceTerminal = true
			}
		}
		if refResourceTerminal {
			return ackerr.ResourceReferenceTerminalFor(
				"Authorizer",
				namespace, *arr.Name)
		}
		if !refResourceSynced {
			return ackerr.ResourceReferenceNotSyncedFor(
				"Authorizer",
				namespace, *arr.Name)
		}
		if obj.Status.AuthorizerID == nil {
			return ackerr.ResourceReferenceMissingTargetFieldFor(
				"Authorizer",
				namespace, *arr.Name,
				"Status.AuthorizerID")
		}
		ko.Spec.AuthorizerID = obj.Status.AuthorizerID
	}
	return nil
}

// resolveReferenceForTarget reads the resource referenced
// from TargetRef field and sets the Target
// from referenced resource
func resolveReferenceForTarget(
	ctx context.Context,
	apiReader client.Reader,
	namespace string,
	ko *svcapitypes.Route,
) error {
	if ko.Spec.TargetRef != nil &&
		ko.Spec.TargetRef.From != nil {
		arr := ko.Spec.TargetRef.From
		if arr == nil || arr.Name == nil || *arr.Name == "" {
			return fmt.Errorf("provided resource reference is nil or empty")
		}
		namespacedName := types.NamespacedName{
			Namespace: namespace,
			Name:      *arr.Name,
		}
		obj := svcapitypes.Integration{}
		err := apiReader.Get(ctx, namespacedName, &obj)
		if err != nil {
			return err
		}
		var refResourceSynced, refResourceTerminal bool
		for _, cond := range obj.Status.Conditions {
			if cond.Type == ackv1alpha1.ConditionTypeResourceSynced &&
				cond.Status == corev1.ConditionTrue {
				refResourceSynced = true
			}
			if cond.Type == ackv1alpha1.ConditionTypeTerminal &&
				cond.Status == corev1.ConditionTrue {
				refResourceTerminal = true
			}
		}
		if refResourceTerminal {
			return ackerr.ResourceReferenceTerminalFor(
				"Integration",
				namespace, *arr.Name)
		}
		if !refResourceSynced {
			return ackerr.ResourceReferenceNotSyncedFor(
				"Integration",
				namespace, *arr.Name)
		}
		if obj.Status.IntegrationID == nil {
			return ackerr.ResourceReferenceMissingTargetFieldFor(
				"Integration",
				namespace, *arr.Name,
				"Status.IntegrationID")
		}
		ko.Spec.Target = obj.Status.IntegrationID
	}
	return nil
}
