// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package api_mapping

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.APIID, b.ko.Spec.APIID) {
		delta.Add("Spec.APIID", a.ko.Spec.APIID, b.ko.Spec.APIID)
	} else if a.ko.Spec.APIID != nil && b.ko.Spec.APIID != nil {
		if *a.ko.Spec.APIID != *b.ko.Spec.APIID {
			delta.Add("Spec.APIID", a.ko.Spec.APIID, b.ko.Spec.APIID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.APIMappingKey, b.ko.Spec.APIMappingKey) {
		delta.Add("Spec.APIMappingKey", a.ko.Spec.APIMappingKey, b.ko.Spec.APIMappingKey)
	} else if a.ko.Spec.APIMappingKey != nil && b.ko.Spec.APIMappingKey != nil {
		if *a.ko.Spec.APIMappingKey != *b.ko.Spec.APIMappingKey {
			delta.Add("Spec.APIMappingKey", a.ko.Spec.APIMappingKey, b.ko.Spec.APIMappingKey)
		}
	}
	if !reflect.DeepEqual(a.ko.Spec.APIRef, b.ko.Spec.APIRef) {
		delta.Add("Spec.APIRef", a.ko.Spec.APIRef, b.ko.Spec.APIRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.DomainName, b.ko.Spec.DomainName) {
		delta.Add("Spec.DomainName", a.ko.Spec.DomainName, b.ko.Spec.DomainName)
	} else if a.ko.Spec.DomainName != nil && b.ko.Spec.DomainName != nil {
		if *a.ko.Spec.DomainName != *b.ko.Spec.DomainName {
			delta.Add("Spec.DomainName", a.ko.Spec.DomainName, b.ko.Spec.DomainName)
		}
	}
	if !reflect.DeepEqual(a.ko.Spec.DomainRef, b.ko.Spec.DomainRef) {
		delta.Add("Spec.DomainRef", a.ko.Spec.DomainRef, b.ko.Spec.DomainRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Stage, b.ko.Spec.Stage) {
		delta.Add("Spec.Stage", a.ko.Spec.Stage, b.ko.Spec.Stage)
	} else if a.ko.Spec.Stage != nil && b.ko.Spec.Stage != nil {
		if *a.ko.Spec.Stage != *b.ko.Spec.Stage {
			delta.Add("Spec.Stage", a.ko.Spec.Stage, b.ko.Spec.Stage)
		}
	}

	return delta
}
